<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class UserSeeder extends Seeder
{
    public function run()
    {
        DB::table('users')->insert([
            [
                'username' => 'admin1',
                'usertype' => 'Admin',
                'name' => 'Dexter Dofinshmert',
                'email' => Hash::make('Dexter@example.com'),
                'password' => Hash::make('admin123'),
                'year_level' => 'Senior',
                'course' => 'Computer Science',
                'remember_token' => Str::random(10),
                'created_at' => now(),
            ],
            [
                'username' => 'admin2',
                'usertype' => 'Admin',
                'name' => 'Adam Smith',
                'email' => Hash::make('Adam@example.com'),
                'password' => Hash::make('admin456'),
                'year_level' => 'Junior',
                'course' => 'Information Technology',
                'remember_token' => Str::random(10),
                'created_at' => now(),
            ],
            [
                'username' => 'admin3',
                'usertype' => 'Admin',
                'name' => 'John Doe',
                'email' => Hash::make('john.doe@example.com'),
                'password' => Hash::make('admin789'),
                'year_level' => 'Senior',
                'course' => 'Computer Science',
                'remember_token' => Str::random(10),
                'created_at' => now(),
            ],
            [
                'username' => 'Jack_Sparrowx44',
                'usertype' => 'Teacher',
                'name' => 'Jack Sparrow',
                'email' => Hash::make('Jack.Sparrow@example.com'),
                'password' => Hash::make('ilovemycat999'),
                'year_level' => 'Junior',
                'course' => 'Information Technology',
                'remember_token' => Str::random(10),
                'created_at' => now(),
            ],
            [
                'username' => 'Will_Turnerx21',
                'usertype' => 'Teacher',
                'name' => 'Will Turner',
                'email' => Hash::make('Will.Turner@example.com'),
                'password' => Hash::make('mypirateadventure'),
                'year_level' => 'Senior',
                'course' => 'Computer Science',
                'remember_token' => Str::random(10),
                'created_at' => now(),
            ],
            [
                'username' => 'Elizabeth_Swanx98',
                'usertype' => 'Teacher',
                'name' => 'Elizabeth Swan',
                'email' => Hash::make('Elizabeth.Swan@example.com'),
                'password' => Hash::make('piratescaptain'),
                'year_level' => 'Junior',
                'course' => 'Information Technology',
                'remember_token' => Str::random(10),
                'created_at' => now(),
            ],
            [
                'username' => 'Barbossa_Captain',
                'usertype' => 'Teacher',
                'name' => 'Hector Barbossa',
                'email' => Hash::make('Barbossa@example.com'),
                'password' => Hash::make('blackpearl123'),
                'year_level' => 'Senior',
                'course' => 'Computer Science',
                'remember_token' => Str::random(10),
                'created_at' => now(),
            ],
            [
                'username' => 'Davy_Jonesx66',
                'usertype' => 'Teacher',
                'name' => 'Davy Jones',
                'email' => Hash::make('Davy.Jones@example.com'),
                'password' => Hash::make('flyingdutchman'),
                'year_level' => 'Junior',
                'course' => 'Information Technology',
                'remember_token' => Str::random(10),
                'created_at' => now(),
            ],
            [
                'username' => 'Adam_lavign',
                'usertype' => 'student',
                'name' => 'Adam Lavign',
                'email' => Hash::make('adam.lavign@example.com'),
                'password' => Hash::make('singmeasong'),
                'year_level' => 'junior',
                'course' => 'Computer Science',
                'remember_token' => Str::random(10),
                'created_at' => now(),
            ],
            [
                'username' => 'Emily_Jonesx22',
                'usertype' => 'student',
                'name' => 'Emily Jones',
                'email' => Hash::make('emily.jones@example.com'),
                'password' => Hash::make('science123'),
                'year_level' => 'senior',
                'course' => 'Biology',
                'remember_token' => Str::random(10),
                'created_at' => now(),
            ],
            [
                'username' => 'Michael_Scottx45',
                'usertype' => 'student',
                'name' => 'Michael Scott',
                'email' => Hash::make('michael.scott@example.com'),
                'password' => Hash::make('worldsbestboss'),
                'year_level' => 'sophomore',
                'course' => 'Business Administration',
                'remember_token' => Str::random(10),
                'created_at' => now(),
            ],
            [
                'username' => 'Sarah_Connorx88',
                'usertype' => 'student',
                'name' => 'Sarah Connor',
                'email' => Hash::make('sarah.connor@example.com'),
                'password' => Hash::make('terminator2023'),
                'year_level' => 'freshman',
                'course' => 'Engineering',
                'remember_token' => Str::random(10),
                'created_at' => now(),
            ],
            [
                'username' => 'John_Wickx50',
                'usertype' => 'student',
                'name' => 'John Wick',
                'email' => Hash::make('john.wick@example.com'),
                'password' => Hash::make('baba-yaga'),
                'year_level' => 'senior',
                'course' => 'Criminal Justice',
                'remember_token' => Str::random(10),
                'created_at' => now(),
            ],
            [
                'username' => 'Lara_Croftx99',
                'usertype' => 'student',
                'name' => 'Lara Croft',
                'email' => Hash::make('lara.croft@example.com'),
                'password' => Hash::make('tombraider123'),
                'year_level' => 'junior',
                'course' => 'Archaeology',
                'remember_token' => Str::random(10),
                'created_at' => now(),
            ],
            [
                'username' => 'Tony_Starkx75',
                'usertype' => 'student',
                'name' => 'Tony Stark',
                'email' => Hash::make('tony.stark@example.com'),
                'password' => Hash::make('ironman2023'),
                'year_level' => 'senior',
                'course' => 'Mechanical Engineering',
                'remember_token' => Str::random(10),
                'created_at' => now(),
            ],
            [
                'username' => 'Elena_Gilbertx66',
                'usertype' => 'student',
                'name' => 'Elena Gilbert',
                'email' => Hash::make('elena.gilbert@example.com'),
                'password' => Hash::make('vampirediaries'),
                'year_level' => 'junior',
                'course' => 'English Literature',
                'remember_token' => Str::random(10),
                'created_at' => now(),
            ],
            [
                'username' => 'Bruce_WayneX88',
                'usertype' => 'student',
                'name' => 'Bruce Wayne',
                'email' => Hash::make('bruce.wayne@example.com'),
                'password' => Hash::make('iamBatman'),
                'year_level' => 'senior',
                'course' => 'Business Administration',
                'remember_token' => Str::random(10),
                'created_at' => now(),
            ],
            [
                'username' => 'Rachel_Greenx34',
                'usertype' => 'student',
                'name' => 'Rachel Green',
                'email' => Hash::make('rachel.green@example.com'),
                'password' => Hash::make('centralperk'),
                'year_level' => 'junior',
                'course' => 'Fashion Design',
                'remember_token' => Str::random(10),
                'created_at' => now(),
            ],
        ]);
    }
}
